/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as UsersRouteImport } from "./routes/users";
import { Route as CalendarRouteImport } from "./routes/calendar";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as RepeatingRidesIndexRouteImport } from "./routes/repeating-rides/index";
import { Route as ProfileIndexRouteImport } from "./routes/profile/index";
import { Route as CalendarIndexRouteImport } from "./routes/calendar/index";
import { Route as RidesDateRouteImport } from "./routes/rides/$date";
import { Route as RideIdRouteImport } from "./routes/ride/$id";
import { Route as RepeatingRidesIdRouteImport } from "./routes/repeating-rides/$id";
import { Route as ProfileIdRouteImport } from "./routes/profile/$id";
import { Route as CalendarDateRouteImport } from "./routes/calendar/$date";
import { Route as RideNewIndexRouteImport } from "./routes/ride/new/index";
import { Route as RideNewDateRouteImport } from "./routes/ride/new/$date";
import { Route as RideEditIdRouteImport } from "./routes/ride/edit/$id";
import { Route as RideCopyIdRouteImport } from "./routes/ride/copy/$id";
import { Route as RepeatingRidesEditIdRouteImport } from "./routes/repeating-rides/edit/$id";
import { Route as RepeatingRidesCopyIdRouteImport } from "./routes/repeating-rides/copy/$id";

const UsersRoute = UsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => rootRouteImport,
} as any);
const CalendarRoute = CalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const RepeatingRidesIndexRoute = RepeatingRidesIndexRouteImport.update({
  id: "/repeating-rides/",
  path: "/repeating-rides/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRouteImport,
} as any);
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => CalendarRoute,
} as any);
const RidesDateRoute = RidesDateRouteImport.update({
  id: "/rides/$date",
  path: "/rides/$date",
  getParentRoute: () => rootRouteImport,
} as any);
const RideIdRoute = RideIdRouteImport.update({
  id: "/ride/$id",
  path: "/ride/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const RepeatingRidesIdRoute = RepeatingRidesIdRouteImport.update({
  id: "/repeating-rides/$id",
  path: "/repeating-rides/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: "/profile/$id",
  path: "/profile/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const CalendarDateRoute = CalendarDateRouteImport.update({
  id: "/$date",
  path: "/$date",
  getParentRoute: () => CalendarRoute,
} as any);
const RideNewIndexRoute = RideNewIndexRouteImport.update({
  id: "/ride/new/",
  path: "/ride/new/",
  getParentRoute: () => rootRouteImport,
} as any);
const RideNewDateRoute = RideNewDateRouteImport.update({
  id: "/ride/new/$date",
  path: "/ride/new/$date",
  getParentRoute: () => rootRouteImport,
} as any);
const RideEditIdRoute = RideEditIdRouteImport.update({
  id: "/ride/edit/$id",
  path: "/ride/edit/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const RideCopyIdRoute = RideCopyIdRouteImport.update({
  id: "/ride/copy/$id",
  path: "/ride/copy/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const RepeatingRidesEditIdRoute = RepeatingRidesEditIdRouteImport.update({
  id: "/repeating-rides/edit/$id",
  path: "/repeating-rides/edit/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const RepeatingRidesCopyIdRoute = RepeatingRidesCopyIdRouteImport.update({
  id: "/repeating-rides/copy/$id",
  path: "/repeating-rides/copy/$id",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/calendar": typeof CalendarRouteWithChildren;
  "/users": typeof UsersRoute;
  "/calendar/$date": typeof CalendarDateRoute;
  "/profile/$id": typeof ProfileIdRoute;
  "/repeating-rides/$id": typeof RepeatingRidesIdRoute;
  "/ride/$id": typeof RideIdRoute;
  "/rides/$date": typeof RidesDateRoute;
  "/calendar/": typeof CalendarIndexRoute;
  "/profile/": typeof ProfileIndexRoute;
  "/repeating-rides/": typeof RepeatingRidesIndexRoute;
  "/repeating-rides/copy/$id": typeof RepeatingRidesCopyIdRoute;
  "/repeating-rides/edit/$id": typeof RepeatingRidesEditIdRoute;
  "/ride/copy/$id": typeof RideCopyIdRoute;
  "/ride/edit/$id": typeof RideEditIdRoute;
  "/ride/new/$date": typeof RideNewDateRoute;
  "/ride/new/": typeof RideNewIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/users": typeof UsersRoute;
  "/calendar/$date": typeof CalendarDateRoute;
  "/profile/$id": typeof ProfileIdRoute;
  "/repeating-rides/$id": typeof RepeatingRidesIdRoute;
  "/ride/$id": typeof RideIdRoute;
  "/rides/$date": typeof RidesDateRoute;
  "/calendar": typeof CalendarIndexRoute;
  "/profile": typeof ProfileIndexRoute;
  "/repeating-rides": typeof RepeatingRidesIndexRoute;
  "/repeating-rides/copy/$id": typeof RepeatingRidesCopyIdRoute;
  "/repeating-rides/edit/$id": typeof RepeatingRidesEditIdRoute;
  "/ride/copy/$id": typeof RideCopyIdRoute;
  "/ride/edit/$id": typeof RideEditIdRoute;
  "/ride/new/$date": typeof RideNewDateRoute;
  "/ride/new": typeof RideNewIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/calendar": typeof CalendarRouteWithChildren;
  "/users": typeof UsersRoute;
  "/calendar/$date": typeof CalendarDateRoute;
  "/profile/$id": typeof ProfileIdRoute;
  "/repeating-rides/$id": typeof RepeatingRidesIdRoute;
  "/ride/$id": typeof RideIdRoute;
  "/rides/$date": typeof RidesDateRoute;
  "/calendar/": typeof CalendarIndexRoute;
  "/profile/": typeof ProfileIndexRoute;
  "/repeating-rides/": typeof RepeatingRidesIndexRoute;
  "/repeating-rides/copy/$id": typeof RepeatingRidesCopyIdRoute;
  "/repeating-rides/edit/$id": typeof RepeatingRidesEditIdRoute;
  "/ride/copy/$id": typeof RideCopyIdRoute;
  "/ride/edit/$id": typeof RideEditIdRoute;
  "/ride/new/$date": typeof RideNewDateRoute;
  "/ride/new/": typeof RideNewIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/calendar"
    | "/users"
    | "/calendar/$date"
    | "/profile/$id"
    | "/repeating-rides/$id"
    | "/ride/$id"
    | "/rides/$date"
    | "/calendar/"
    | "/profile/"
    | "/repeating-rides/"
    | "/repeating-rides/copy/$id"
    | "/repeating-rides/edit/$id"
    | "/ride/copy/$id"
    | "/ride/edit/$id"
    | "/ride/new/$date"
    | "/ride/new/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/users"
    | "/calendar/$date"
    | "/profile/$id"
    | "/repeating-rides/$id"
    | "/ride/$id"
    | "/rides/$date"
    | "/calendar"
    | "/profile"
    | "/repeating-rides"
    | "/repeating-rides/copy/$id"
    | "/repeating-rides/edit/$id"
    | "/ride/copy/$id"
    | "/ride/edit/$id"
    | "/ride/new/$date"
    | "/ride/new";
  id:
    | "__root__"
    | "/"
    | "/calendar"
    | "/users"
    | "/calendar/$date"
    | "/profile/$id"
    | "/repeating-rides/$id"
    | "/ride/$id"
    | "/rides/$date"
    | "/calendar/"
    | "/profile/"
    | "/repeating-rides/"
    | "/repeating-rides/copy/$id"
    | "/repeating-rides/edit/$id"
    | "/ride/copy/$id"
    | "/ride/edit/$id"
    | "/ride/new/$date"
    | "/ride/new/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CalendarRoute: typeof CalendarRouteWithChildren;
  UsersRoute: typeof UsersRoute;
  ProfileIdRoute: typeof ProfileIdRoute;
  RepeatingRidesIdRoute: typeof RepeatingRidesIdRoute;
  RideIdRoute: typeof RideIdRoute;
  RidesDateRoute: typeof RidesDateRoute;
  ProfileIndexRoute: typeof ProfileIndexRoute;
  RepeatingRidesIndexRoute: typeof RepeatingRidesIndexRoute;
  RepeatingRidesCopyIdRoute: typeof RepeatingRidesCopyIdRoute;
  RepeatingRidesEditIdRoute: typeof RepeatingRidesEditIdRoute;
  RideCopyIdRoute: typeof RideCopyIdRoute;
  RideEditIdRoute: typeof RideEditIdRoute;
  RideNewDateRoute: typeof RideNewDateRoute;
  RideNewIndexRoute: typeof RideNewIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/users": {
      id: "/users";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof UsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/calendar": {
      id: "/calendar";
      path: "/calendar";
      fullPath: "/calendar";
      preLoaderRoute: typeof CalendarRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repeating-rides/": {
      id: "/repeating-rides/";
      path: "/repeating-rides";
      fullPath: "/repeating-rides/";
      preLoaderRoute: typeof RepeatingRidesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/": {
      id: "/profile/";
      path: "/profile";
      fullPath: "/profile/";
      preLoaderRoute: typeof ProfileIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/calendar/": {
      id: "/calendar/";
      path: "/";
      fullPath: "/calendar/";
      preLoaderRoute: typeof CalendarIndexRouteImport;
      parentRoute: typeof CalendarRoute;
    };
    "/rides/$date": {
      id: "/rides/$date";
      path: "/rides/$date";
      fullPath: "/rides/$date";
      preLoaderRoute: typeof RidesDateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ride/$id": {
      id: "/ride/$id";
      path: "/ride/$id";
      fullPath: "/ride/$id";
      preLoaderRoute: typeof RideIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repeating-rides/$id": {
      id: "/repeating-rides/$id";
      path: "/repeating-rides/$id";
      fullPath: "/repeating-rides/$id";
      preLoaderRoute: typeof RepeatingRidesIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/$id": {
      id: "/profile/$id";
      path: "/profile/$id";
      fullPath: "/profile/$id";
      preLoaderRoute: typeof ProfileIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/calendar/$date": {
      id: "/calendar/$date";
      path: "/$date";
      fullPath: "/calendar/$date";
      preLoaderRoute: typeof CalendarDateRouteImport;
      parentRoute: typeof CalendarRoute;
    };
    "/ride/new/": {
      id: "/ride/new/";
      path: "/ride/new";
      fullPath: "/ride/new/";
      preLoaderRoute: typeof RideNewIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ride/new/$date": {
      id: "/ride/new/$date";
      path: "/ride/new/$date";
      fullPath: "/ride/new/$date";
      preLoaderRoute: typeof RideNewDateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ride/edit/$id": {
      id: "/ride/edit/$id";
      path: "/ride/edit/$id";
      fullPath: "/ride/edit/$id";
      preLoaderRoute: typeof RideEditIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ride/copy/$id": {
      id: "/ride/copy/$id";
      path: "/ride/copy/$id";
      fullPath: "/ride/copy/$id";
      preLoaderRoute: typeof RideCopyIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repeating-rides/edit/$id": {
      id: "/repeating-rides/edit/$id";
      path: "/repeating-rides/edit/$id";
      fullPath: "/repeating-rides/edit/$id";
      preLoaderRoute: typeof RepeatingRidesEditIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repeating-rides/copy/$id": {
      id: "/repeating-rides/copy/$id";
      path: "/repeating-rides/copy/$id";
      fullPath: "/repeating-rides/copy/$id";
      preLoaderRoute: typeof RepeatingRidesCopyIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface CalendarRouteChildren {
  CalendarDateRoute: typeof CalendarDateRoute;
  CalendarIndexRoute: typeof CalendarIndexRoute;
}

const CalendarRouteChildren: CalendarRouteChildren = {
  CalendarDateRoute: CalendarDateRoute,
  CalendarIndexRoute: CalendarIndexRoute,
};

const CalendarRouteWithChildren = CalendarRoute._addFileChildren(
  CalendarRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRouteWithChildren,
  UsersRoute: UsersRoute,
  ProfileIdRoute: ProfileIdRoute,
  RepeatingRidesIdRoute: RepeatingRidesIdRoute,
  RideIdRoute: RideIdRoute,
  RidesDateRoute: RidesDateRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RepeatingRidesIndexRoute: RepeatingRidesIndexRoute,
  RepeatingRidesCopyIdRoute: RepeatingRidesCopyIdRoute,
  RepeatingRidesEditIdRoute: RepeatingRidesEditIdRoute,
  RideCopyIdRoute: RideCopyIdRoute,
  RideEditIdRoute: RideEditIdRoute,
  RideNewDateRoute: RideNewDateRoute,
  RideNewIndexRoute: RideNewIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
