name: RiderHQ Membership
on:
  workflow_dispatch:

jobs:
  membership:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest RiderHQ membership info
        run: |
          curl \
          --request POST \
          --url "https://api.fairhursts.net/riderhq" \
          --header "Authorization: Bearer ${{ secrets.API_KEY }}"
